### ISSUE TITLE
Add a nightly job for testing the cloned ECP module

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls-test#103]
We are making a copy of the ECP module (https://github.com/Mbed-TLS/mbedtls/issues/7598). We are only adding limited testing in the PR job to save CI bandwidth. We still need an extensive testing for the copy and would like to do a full CI run with the cloned ECP module on.

The task is to set up a nightly job that does a full CI run on development with the new ECP module on and only members of the bignum team get notifications about it.

(Ask @bensze01 for help if needed.)

**Comment by gilles-peskine-arm** [comment]
I don't understand why we would use this approach.

It's a separate nightly job so if we break something in a pull request, we won't know it until the code has been merged. It's extra work to run and monitor this job, and the person monitoring the job won't necessarily know what's going on with the changes.

We don't expect changes to the new bignum itself, but it can be affected by global changes, e.g. to platform functions (like zeroization), to build scripts, to the test framework...

> would like to do a full CI run with the cloned ECP module on.

Why would we run the whole CI? Why not just run the unit tests in the full configuration — once on 64-bit and once on 32-bit? (Also little vs big endian once we have that.) I don't understand why we'd want test the full matrix of configurations against that particular option. We don't do that for everest and p256-m, why would we do it for this ECC implementation?

**Comment by yanesca** [comment]
It is a separate job because the idea was that the bignum team would monitor this job and we wouldn't inconvenience the rest of the team (This was before the bignum work was paused.)

> We don't do that for everest and p256-m, why would we do it for this ECC implementation?

Because unlike those, this eventually will become part of the codebase that will need to pass the full CI when we remove the flag and integrate the new module.

It is a full run, because if we would develop it without cloning, we would get a full CI run with the new code and when we remove the flag, the code will need to pass the full CI. Like this we can be confident that the new code passes the full CI when the flag is removed. If we run a subset, there is always the possibility that we are not as clever as we think we are. How big this residual risk is arguable of course, but I since this is a nightly run, I think the cost should be acceptable.

**Comment by gilles-peskine-arm** [comment]
Note from today's team call: I hadn't realized that we were doing this _in addition to_ regular `all.sh` jobs. I thought this was proposed as a substitute to `all.sh` jobs.

As long as we are testing the new code in `all.sh` with sufficient coverage, I have no objection in terms of risk. Considering the nature of the feature, I think sufficient coverage would be one 64-bit build and one 32-bit build, both running unit tests with Asan.

With respect to additional testing, I don't think the extra complexity is worth it. We are adding new complexity in `all.sh` (which is already too complex as it is, and overdue for a python rewrite). We are also adding complexity to the CI systems, which historically have not been reliable. There's little risk that the new bignum will break exotic configurations as long as it's passing its unit tests. Perhaps misplaced ifdefs that break certain sets of ECC curves, but that's easily resolved. There may be warnings from some compilers on the new bignum, but that too is easily resolved. So I think we're making a bad trade-off here in terms of amount of work vs benefit. But I won't oppose this design.

**Comment by yanesca** [comment]
See https://github.com/Mbed-TLS/mbedtls/pull/7824#issuecomment-1650182783
