### ISSUE TITLE
Consider using GitHub merge queues

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls-test#105]
We currently run our main CI on a branch's head only, not on the merge result. Sometimes we have two pull requests which are ok on their own, but have a conflict that GitHub can't detect. Then both PR's CI passes but if we merge them both then the resulting branch is broken.

A recent example: https://github.com/Mbed-TLS/mbedtls/pull/7699 was needed to fix an undetected conflict (one PR moves a file, another PR adds a reference to the old file location).

We used to run a CI on the merge result. But we were still willing to merge PR1 and PR2 if they both had passing CI, even if the result of merging both together had not been tested. So it wouldn't have helped with the #7699 incident.

Since February 2023, GitHub has a [merge queue](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) feature. You can [set up  a merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue), and then [tell GitHub to merge only if additional checks pass](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue). GitHub takes care of serializing pull requests and cancelling the merge if the merge-time checks fail.

The goal of this issue is:

1. Research the merge queue feature. Check that there is no limitation that would prevent us from using it. List what would need to change in our project documentation.
2. Define a subset of the CI to run on the merge queue. We can't realistically run everything. The focus should be on things that are likely to pass independently but fail together even when there is no git conflict.
3. Turn on merge queues for https://github.com/Mbed-TLS/mbedtls (and -restricted, I guess) and update any relevant documentation.

Note: this is filed in `mbedtls-test` because it's mostly relevant for testing, but it might not affect the `mbedtls-test` repository at all.

**Comment by bensze01** [comment]
Merge queues have been implemented in #117. Closing.
