### ISSUE TITLE
"Result analysis" overwrites status from failed `all.sh` components

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls-test#120]
On a PR that has both failed `all.sh` components, and also a failure in `analyze_outcomes.py`, the only thing reported in the github status is "Result analysis failed".

Expected behaviour: report "all-u16-xxx all-u16-yyy and Result analysis failed" - or something similar that includes all the failures (as far as size limitations allow, as usual).

**Comment by mpg** [comment]
Examples from the current state of https://github.com/Mbed-TLS/mbedtls/pull/7861

![Screenshot from 2023-08-01 11-29-12](https://github.com/Mbed-TLS/mbedtls-test/assets/60640/164f113d-e74c-4460-a96c-ff1deedf594c)
![Screenshot from 2023-08-01 11-29-41](https://github.com/Mbed-TLS/mbedtls-test/assets/60640/08b5ca1b-9032-4272-be7b-19c3a607eb07)

**Comment by gilles-peskine-arm** [comment]
To fix this, we should add outcome analysis to the dictionary that records failed components. This would also take care of the email reporting for nightly jobs, which omits outcome analysis from the list of reported failures.
