### ISSUE TITLE
Run self test 

### ISSUE THREAD

**Issue by PrithviAPai** [Mbed-TLS/mbedtls-test#136]
Hi Team,

I have integrated mbedTLS to my requirement. 
Now I m required to get FIPS certification for the same. 
Does mbedTLS provide any example code on how self test and KAT are run ? 
Can some examples be shared ? It will help me integrating self test and KAT in the mbedTLS library.

**Comment by gilles-peskine-arm** [comment]
This repository contains the continuous integration scripts for Mbed TLS. It has nothing to do with self-tests for FIPS certification.
