### ISSUE TITLE
Nightly CI on restyled code

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls-test#78]
Run a full CI nightly on the [restyled code](https://github.com/Mbed-TLS/mbedtls/issues/6346), until we [switch to it](https://github.com/Mbed-TLS/mbedtls/issues/6359). This will help confirm that the restyled code works.

To be determined: how do we arrange this?

* Set up a nightly job on one of the CIs (one is enough).
* Have it restyle before *all* of the builds. For `all.sh`-based builds we can do this in `all.sh`, but what about Windows? As an intermediate stage, we might skip Windows in this job, to be added once we have a solution.

**Comment by gilles-peskine-arm** [comment]
It doesn't seem worth it to fully automate. So what we're doing instead is a manual push ([scripted](https://github.com/Mbed-TLS/mbedtls/pull/6758), but with a human pressing the button) followed by CI runs.

Maybe we can automated the CI runs though? They'd have to run on the two preview branches.

**Comment by davidhorstmann-arm** [comment]
Closing as this has been set up
