### ISSUE TITLE
Add Dockerfile of ubuntu-22.04

### ISSUE THREAD

**Issue by yanrayw** [Mbed-TLS/mbedtls-test#87]
In some scenarios, we need to set up a test environment of ubuntu-22.04. See this issue: https://github.com/Mbed-TLS/mbedtls/issues/6658

I think it's better to add Dockerfile of ubuntu-22.04 like other ubuntu versions.

**Comment by gilles-peskine-arm** [comment]
We already have an issue for this: https://github.com/Mbed-TLS/mbedtls-test/issues/58
